In [ ]:
from fastai.basics import *
from fastai.vision.all import *

/home/tiago/anaconda3/envs/fastai/lib/python3.9/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /opt/conda/conda-bld/pytorch_1607370151529/work/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0


In [ ]:
%load_ext autoreload
%autoreload 2

In [ ]:
from gw_dset import Data_GW

In [ ]:
from my_utils import np_to_tensor

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
n_classes = 22
view = 'encoded1234'

In [ ]:
def get_stats(ds):
    means, stds = torch.zeros(4), torch.zeros(4)
    for sample in ds:
        means += sample[0].mean(dim=[1, 2])
        stds += sample[0].std(dim=[1, 2])
    means = means/len(ds)
    stds = stds/len(ds)
    return means, stds

### v1

In [ ]:
DATASET_PATH = "./datasets/Real_GWs_v1"
ds = Data_GW(dataset_path=DATASET_PATH, view=view, transform=np_to_tensor)

In [ ]:
get_stats(ds)

(tensor([0.1845, 0.1821, 0.1822, 0.1809]),
 tensor([0.0691, 0.0660, 0.0660, 0.0636]))

### v2

In [ ]:
DATASET_PATH = "./datasets/Real_GWs_v2"
ds = Data_GW(dataset_path=DATASET_PATH, view=view, transform=np_to_tensor)

In [ ]:
get_stats(ds)

(tensor([0.1896, 0.1875, 0.1853, 0.1807]),
 tensor([0.0773, 0.0724, 0.0686, 0.0635]))

### v3

In [ ]:
DATASET_PATH = "./datasets/Real_GWs_v3"
ds = Data_GW(dataset_path=DATASET_PATH, view=view, transform=np_to_tensor)

In [ ]:
get_stats(ds)

(tensor([0.1594, 0.1584, 0.1569, 0.1531]),
 tensor([0.0530, 0.0504, 0.0476, 0.0427]))

### v4

In [ ]:
DATASET_PATH = "./datasets/Real_GWs_v4"
ds = Data_GW(dataset_path=DATASET_PATH, view=view, transform=np_to_tensor)

In [ ]:
get_stats(ds)

(tensor([0.1729, 0.1717, 0.1702, 0.1688]),
 tensor([0.0570, 0.0554, 0.0520, 0.0495]))